services:
  traefik:
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN_BASE}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${DASHBOARD_AUTH}"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"


  app1:
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app1.loadbalancer.server.port=8080"
      # HTTP router
      - "traefik.http.routers.app1-http.entrypoints=web"
      - "traefik.http.routers.app1-http.rule=Host(`${DOMAIN1}`)"
      # HTTPS router
      - "traefik.http.routers.app1-secure.entrypoints=websecure"
      - "traefik.http.routers.app1-secure.rule=Host(`${DOMAIN1}`)"
      - "traefik.http.routers.app1-secure.tls.certresolver=myresolver"

  app2:
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app2.loadbalancer.server.port=80"
      # HTTP router
      - "traefik.http.routers.app2-http.entrypoints=web"
      - "traefik.http.routers.app2-http.rule=Host(`${DOMAIN2}`)"
      # HTTPS router
      - "traefik.http.routers.app2-secure.entrypoints=websecure"
      - "traefik.http.routers.app2-secure.rule=Host(`${DOMAIN2}`)"
      - "traefik.http.routers.app2-secure.tls.certresolver=myresolver"

  app3:
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app3.loadbalancer.server.port=80"
      # HTTP router
      - "traefik.http.routers.app3-http.entrypoints=web"
      - "traefik.http.routers.app3-http.rule=Host(`${DOMAIN3}`)"
      # HTTPS router
      - "traefik.http.routers.app3-secure.entrypoints=websecure"
      - "traefik.http.routers.app3-secure.rule=Host(`${DOMAIN3}`)"
      - "traefik.http.routers.app3-secure.tls.certresolver=myresolver"

  app5:
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app5.loadbalancer.server.port=8080"
      # HTTP router
      - "traefik.http.routers.app5-http.entrypoints=web"
      - "traefik.http.routers.app5-http.rule=Host(`${DOMAIN5}`)"
      # HTTPS router
      - "traefik.http.routers.app5-secure.entrypoints=websecure"
      - "traefik.http.routers.app5-secure.rule=Host(`${DOMAIN5}`)"
      - "traefik.http.routers.app5-secure.tls.certresolver=myresolver"

volumes:
  letsencrypt:
