services:
  traefik:
    image: traefik:v3.3.3
    command:
      - "--providers.docker=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik_default

  app-go:
    build: app-go
    expose:
      - "8080"
    networks:
      - traefik_default

  app-php-simple:
    build: app-php-simple
    expose:
      - "80"
    env_file:
      - path: ./.env
        required: true
    networks:
      - traefik_default

  app-html:
    build: app-html
    expose:
      - "80"
    volumes:
      - "./app-html/public:/usr/share/nginx/html:ro"
      - "./app-html/nginx.conf:/etc/nginx/conf.d/default.conf:rw"
    networks:
      - traefik_default

  app-php-laravel:
    build: app-php-laravel
    expose:
      - "80"
    volumes:
      - ./app-php-laravel/api-laravel:/app:rw
    networks:
      - traefik_default

  app-rust-simple:
    build: app-rust-simple
    expose:
      - "8080"
    networks:
      - traefik_default

networks:
  traefik_default:
    driver: bridge
