services:
  traefik:
    image: traefik:v3.3.3
    command:
      - "--providers.docker=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik_default

  app1:
    build: ./app1
    expose:
      - "8080"
    networks:
      - traefik_default

  app2:
    build: ./app2
    expose:
      - "80"
    networks:
      - traefik_default

  app3:
    build: ./app3
    expose:
      - "80"
    networks:
      - traefik_default

networks:
  traefik_default:
    driver: bridge
